version: 2.1
jobs:
  test:
    parameters:
      elixir_version:
        type: string
    working_directory: ~/repo
    docker:
      - image: cimg/elixir:<<parameters.elixir_version>>
        environment:
          - MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "mix.lock" }}
      - run:
          name: Install dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run: mix compile
      - save_cache:
          paths:
            - deps
            - .mix
          key: v2-dependencies-{{ checksum "mix.lock" }}
      - run: mix test --exclude not_implemented
      - when:
          condition:
            not:
              matches:
                pattern: "^1\\.(?:9|10|11)\\.\\d+$"
                value: <<parameters.elixir_version>>
          steps:
            - run: mix format --check-formatted
workflows:
  test_versions:
    jobs:
      - test:
          matrix:
            parameters:
              elixir_version:
                - 1.14.2
                - 1.13.4
                - 1.12.3
                - 1.11.4
                - 1.10.4
                - 1.9.4
